CREATE DATABASE Senai_SPMedGroup_Manha;

USE Senai_SPMedGroup_Manha;

CREATE TABLE Tipo_Usuario(
ID INT IDENTITY PRIMARY KEY
,Tipo VARCHAR(13) NOT NULL
);

CREATE TABLE Usuario(
ID INT IDENTITY PRIMARY KEY
,Email VARCHAR(250) NOT NULL
,Senha VARCHAR(250) NOT NULL
,Tipo INT FOREIGN KEY REFERENCES Tipo_Usuario(ID)
);

CREATE TABLE Prontuario(
ID_Usuario INT FOREIGN KEY REFERENCES Usuario(ID) NOT NULL
,Nome VARCHAR(100) NOT NULL
,Sobrenome VARCHAR(200) NOT NULL
,Data_Nascimento DATE NOT NULL
,CPF CHAR(14) NOT NULL
,RG CHAR(9) NOT NULL
,Telefone CHAR(11) NOT NULL
,Logradouro VARCHAR(250) NOT NULL
,Numero_Predio INT NOT NULL
,Complemento VARCHAR(50) NULL
,CIDADE VARCHAR(200) NOT NULL
,Estado VARCHAR(200) NOT NULL
,UF CHAR(2) NOT NULL
,CEP CHAR(8) NOT NULL
);

CREATE TABLE Especialidade(
ID INT IDENTITY PRIMARY KEY
,Nome VARCHAR(150) NOT NULL
);

CREATE TABLE Situacao(
ID INT IDENTITY PRIMARY KEY
,Nome VARCHAR(100) NOT NULL
);

CREATE TABLE Clinica(
ID INT IDENTITY PRIMARY KEY,
,Nome_Fantasia VARCHAR(250) NOT NULL 
,Razao_Social VARCHAR(250) NOT NULL
,Endereco VARCHAR (250) NOT NULL 
,CEP CHAR (8) NOT NULL
,CNPJ CHAR (14) NOT NULL
,Horario_Abertura TIME NOT NULL
,Horario_Fechamento TIME NOT NULL
,Logradouro VARCHAR(250) NOT NULL 
);